# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
