# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20160911_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
